# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 

# Model Form Field configuration
form: $/beltechsoft/forms/models/type/fields.yaml

# Model Class name
modelClass: Beltechsoft\Forms\Models\Type

# Default redirect location
defaultRedirect: beltechsoft/forms/types

# Create page
create:
    title: backend::lang.form.create_title
    redirect: beltechsoft/forms/types/update/:id
    redirectClose: beltechsoft/forms/types

# Update page
update:
    title: backend::lang.form.update_title
    redirect: beltechsoft/forms/types
    redirectClose: beltechsoft/forms/types

# Preview page
preview:
    title: backend::lang.form.preview_title
